services:
  - type: web
    name: ataturk-digital-twin
    runtime: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y ffmpeg

    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT